name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Install dependencies
      run: npm install --prefix lambda/custom/ --production

    - name: Run tests
      run: npm test --prefix lambda/custom/

    - name: Build skill
      run: npm run-script build --prefix lambda/custom/

    - name: Create zip file
      run: cd lambda/custom && zip -r -X file.zip ./ && cd .. && cd ..

    - name: AWS Lambda Deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: tech-weeklies-skill
        zip_file: lambda/custom/file.zip

